import { EstimateForm, Footer, Header, Icon, ServiceAreas } from "../site-components";

const floorData: Record<string, { title: string; intro: string; image: string; benefits: string[]; ideal: string; care: string }> = {
  "luxury-vinyl": { title: "Luxury Vinyl Flooring", intro: "Natural wood and stone looks with the water resistance and easy care that busy Calgary homes need.", image: "https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?auto=format&fit=crop&w=1800&q=88", benefits: ["Water-resistant options", "Comfortable underfoot", "Easy everyday care", "Wide range of wood and stone looks"], ideal: "Basements, kitchens, entryways, family rooms, rentals and pet-friendly homes.", care: "Vacuum or sweep regularly and damp-mop with a manufacturer-approved cleaner." },
  laminate: { title: "Laminate Flooring", intro: "Durable, style-forward flooring that delivers a convincing wood look at an approachable price.", image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1800&q=88", benefits: ["Scratch-resistant wear layers", "Many realistic finishes", "Good value", "Straightforward maintenance"], ideal: "Living rooms, bedrooms, hallways, home offices and active households.", care: "Sweep regularly, wipe spills promptly and avoid standing water." },
  hardwood: { title: "Hardwood Flooring", intro: "Authentic warmth, natural variation and lasting value for spaces that deserve something timeless.", image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1800&q=88", benefits: ["Natural character", "Long service life", "Refinishing potential", "Timeless appeal"], ideal: "Living rooms, dining rooms, bedrooms and main-floor gathering spaces.", care: "Use felt furniture pads, control indoor humidity and clean with hardwood-safe products." },
  carpet: { title: "Carpet Flooring", intro: "Softness, warmth and sound control in a broad range of colours, textures and performance levels.", image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1800&q=88", benefits: ["Warm and comfortable", "Quieter rooms", "Many textures and colours", "Family-friendly options"], ideal: "Bedrooms, stairs, media rooms, playrooms and cozy lower-level spaces.", care: "Vacuum consistently and arrange periodic professional cleaning based on use." },
  tile: { title: "Tile Flooring", intro: "Durable, moisture-ready surfaces with endless possibilities for pattern, scale and texture.", image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1800&q=88", benefits: ["Excellent water resistance", "Highly durable", "Easy to clean", "Works with radiant heat"], ideal: "Bathrooms, kitchens, mudrooms, entries and commercial spaces.", care: "Sweep and mop routinely; maintain grout with products suited to the tile type." },
};

const serviceAreaCopy: Record<string, string> = { calgary: "From established inner-city homes to new suburban builds, we help Calgary clients select floors suited to Alberta’s climate and everyday life.", chestermere: "Our home community. Visit the Floorify showroom on Marina Drive, compare materials in person and plan your Chestermere flooring project with our local team.", airdrie: "Floorify brings product guidance, professional measurement and installation planning to homes and businesses throughout Airdrie.", cochrane: "Choose flooring that complements Cochrane’s relaxed, natural character—with practical advice for performance, care and installation.", okotoks: "We help Okotoks homeowners and businesses find durable, considered flooring solutions for renovations and new spaces.", strathmore: "Floorify serves Strathmore with thoughtful product selection, in-home measurement and professional flooring installation." };

export default async function ContentPage({ params }: { params: Promise<{ slug: string[] }> }) {
  const { slug } = await params;
  const path = slug.join("/");
  const floorKey = slug[0] === "flooring" ? slug[1] : "";
  if (floorData[floorKey]) return <FloorPage data={floorData[floorKey]} />;
  if (slug[0] === "service-areas" && serviceAreaCopy[slug[1]]) return <AreaPage city={slug[1]} copy={serviceAreaCopy[slug[1]]} />;
  if (path === "flooring") return <ListingPage type="flooring" />;
  if (path === "services") return <ListingPage type="services" />;
  if (path === "about") return <AboutPage />;
  if (path === "showroom" || path === "projects") return <ShowroomPage title={path === "projects" ? "Project Inspiration" : "Visit Our Showroom"} />;
  return <GenericPage title={path.split("/").pop()?.replaceAll("-", " ") || "Floorify Canada"} />;
}

function PageHero({ title, intro, image }: { title: string; intro: string; image?: string }) { return <section className="inner-hero" style={image ? { backgroundImage: `linear-gradient(90deg, rgba(23,29,26,.88),rgba(23,29,26,.3)),url(${image})` } : undefined}><div className="shell"><p className="eyebrow light">Floorify Canada</p><h1>{title}</h1><p>{intro}</p><a className="button button-primary" href="#estimate">Book a free estimate <Icon name="arrow" /></a></div></section>; }
function FloorPage({ data }: { data: typeof floorData[string] }) { return <><Header/><main><PageHero title={data.title} intro={data.intro} image={data.image}/><section className="section shell detail-grid"><div><p className="eyebrow">Why choose it</p><h2>Performance meets personal style</h2><p>Every floor has a different job to do. We’ll help you compare construction, finish, durability and price so the product you choose fits your space—not just the sample board.</p><ul className="benefit-grid">{data.benefits.map(b=><li key={b}><Icon name="check"/>{b}</li>)}</ul></div><aside><h3>Best suited for</h3><p>{data.ideal}</p><h3>Simple care</h3><p>{data.care}</p><p className="note">Product performance and warranty vary by manufacturer. We’ll review the specifications of your selected floor before installation.</p></aside></section><section className="section soft"><div className="shell"><p className="eyebrow">Our process</p><h2>Measured, planned and installed with care</h2><div className="steps three"><div><b>01</b><h3>Explore</h3><p>Compare samples, colours and practical features.</p></div><div><b>02</b><h3>Measure</h3><p>Confirm quantities, site conditions and preparation.</p></div><div><b>03</b><h3>Install</h3><p>Complete the work and walk through the finished floor.</p></div></div></div></section><EstimateBlock/></main><Footer/></>; }
function AreaPage({ city, copy }: { city:string; copy:string }) { const name=city[0].toUpperCase()+city.slice(1); return <><Header/><main><PageHero title={`Flooring in ${name}`} intro={copy} image="https://images.unsplash.com/photo-1560184897-ae75f418493e?auto=format&fit=crop&w=1800&q=88"/><section className="section shell detail-grid"><div><p className="eyebrow">Local flooring help</p><h2>Products and installation for your whole space</h2><p>Explore luxury vinyl, laminate, hardwood, carpet and tile with help from a team that understands local homes, Alberta’s seasonal conditions and the realities of an active household.</p><div className="button-row"><a className="button button-dark" href="/flooring">Explore flooring</a><a className="text-link" href="/showroom">Visit the showroom <Icon name="arrow"/></a></div></div><aside><h3>Services in {name}</h3><ul className="plain-list"><li>Flooring consultation</li><li>In-home measurement</li><li>Product selection</li><li>Professional installation</li><li>Residential and commercial projects</li></ul></aside></section><ServiceAreas/><EstimateBlock/></main><Footer/></>; }
function ListingPage({ type }: { type:"flooring"|"services" }) { const flooring=Object.entries(floorData); return <><Header/><main><PageHero title={type==="flooring"?"Flooring for every kind of space":"Flooring services, from start to finish"} intro={type==="flooring"?"Compare beautiful, dependable options with guidance from a local flooring specialist.":"Thoughtful advice, accurate planning and careful installation—coordinated by one local team."}/><section className="section shell">{type==="flooring"?<div className="simple-cards">{flooring.map(([key,d])=><a href={`/flooring/${key}`} key={key}><h2>{d.title}</h2><p>{d.intro}</p><span>Learn more <Icon name="arrow"/></span></a>)}</div>:<div className="simple-cards"><article><h2>Design consultation</h2><p>Compare colours, textures and performance options with a specialist in our Chestermere showroom.</p></article><article><h2>In-home measurement</h2><p>Get accurate quantities and identify the preparation your project may need.</p></article><article><h2>Professional installation</h2><p>Careful installation coordinated around your product, site and schedule.</p></article><article><h2>Commercial flooring</h2><p>Durable materials and practical planning for high-traffic business environments.</p></article></div>}</section><EstimateBlock/></main><Footer/></>; }
function AboutPage(){return <><Header/><main><PageHero title="A local team, invested in your space" intro="For more than 10 years, Floorify Canada has helped homeowners and businesses turn flooring ideas into finished rooms." image="https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=1800&q=88"/><section className="section shell story"><div><p className="eyebrow">Our approach</p><h2>Good flooring starts with good guidance.</h2></div><div><p>A floor changes the way a room looks, feels and works. We take the time to understand the space, explain the trade-offs and guide each client toward a choice they can feel confident about.</p><p>From our Chestermere showroom to the final installation walkthrough, our goal is a straightforward, attentive experience.</p></div></section><section className="stats"><div className="shell"><div><strong>10+</strong><span>years in business</span></div><div><strong>252</strong><span>happy clients</span></div><div><strong>6</strong><span>communities served</span></div></div></section><ServiceAreas/><EstimateBlock/></main><Footer/></>}
function ShowroomPage({title}:{title:string}){return <><Header/><main><PageHero title={title} intro="See materials up close, compare finishes in natural light and get expert help narrowing your options." image="https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1800&q=88"/><section className="section shell detail-grid"><div><p className="eyebrow">100 Marina Drive #405</p><h2>Bring your ideas. Leave with clarity.</h2><p>Visit Monday through Saturday from 10 a.m. to 5 p.m. Bring room photos, inspiration and rough measurements if you have them. We’ll help you compare the options that make sense for your space.</p><a className="button button-dark" href="https://floorifycanada.ca/floorify-virtual-showroom" target="_blank" rel="noreferrer">Open virtual showroom <Icon name="arrow"/></a></div><aside><h3>Showroom details</h3><p>100 Marina Dr #405<br/>Chestermere, AB T1X 0A9</p><p>Monday–Saturday<br/>10 a.m.–5 p.m.</p><a className="text-link" href="https://www.google.com/maps/place/Floorify+Canada/@51.0480889,-113.8292758,17z" target="_blank" rel="noreferrer">Get directions <Icon name="arrow"/></a></aside></section><EstimateBlock/></main><Footer/></>}
function GenericPage({title}:{title:string}){return <><Header/><main><PageHero title={title.replace(/^./,c=>c.toUpperCase())} intro="Connect with Floorify Canada for helpful flooring guidance and a clear next step for your project."/><EstimateBlock/></main><Footer/></>}
function EstimateBlock(){return <section className="estimate-section" id="estimate"><div className="shell estimate-grid"><div><p className="eyebrow light">Free estimate</p><h2>Tell us about your project.</h2><p>Share your goals and a Floorify specialist will help you plan the next step.</p></div><EstimateForm/></div></section>}
